#!/usr/bin/env python3
"""
gen_unicode_tables.py - Generate pzpdir_unicode.h, the Unicode tables of the word index tokenizer.

Tokenizer v1 (spec §3.7) must reproduce Python's `re.findall(r'\\w+', text.lower())` exactly, so the C
side needs Python's view of Unicode:
  - which code points `str.lower()` changes, and into what (one code point, or two for U+0130);
  - which code points are word characters for `re` (`str.isalnum()` or '_').
The tables are taken from the running Python's unicodedata; its Unicode version is recorded in the
header, and the parity tests must use a Python with the same version.

Usage:
    python3 scripts/gen_unicode_tables.py > pzpdir_unicode.h

Repository : https://github.com/AmmarkoV/PZP
Author     : Ammar Qammaz (AmmarkoV)
"""

import sys
import unicodedata


def code_points():
    """Every Unicode scalar value (no surrogates)."""
    return (c for c in range(0x110000) if not 0xD800 <= c <= 0xDFFF)


def word_ranges():
    """Inclusive (first, last) ranges of the code points `re` treats as \\w."""
    ranges = []
    for c in code_points():
        if chr(c).isalnum() or c == 0x5F:
            if ranges and ranges[-1][1] == c - 1:
                ranges[-1][1] = c
            else:
                ranges.append([c, c])
    return ranges


def lower_map():
    """(code point, first, second) for every code point str.lower() changes; second is 0 when unused."""
    out = []
    for c in code_points():
        low = chr(c).lower()
        if low == chr(c):
            continue
        if len(low) > 2:
            raise SystemExit("U+%04X lowers to %d code points; the table holds at most 2" % (c, len(low)))
        out.append((c, ord(low[0]), ord(low[1]) if len(low) == 2 else 0))
    return out


def main():
    words = word_ranges()
    lower = lower_map()
    w = sys.stdout.write
    w("/** @file pzpdir_unicode.h\n")
    w(" *  @brief Unicode tables of the word index tokenizer (spec §3.7). GENERATED by\n")
    w(" *  scripts/gen_unicode_tables.py from Python %s (Unicode %s): do not edit by hand. */\n"
      % (sys.version.split()[0], unicodedata.unidata_version))
    w("#ifndef PZPDIR_UNICODE_H_INCLUDED\n#define PZPDIR_UNICODE_H_INCLUDED\n\n")
    w("#include <stdint.h>\n\n")
    w("/** @brief Unicode version the tables were generated from. */\n")
    w("#define PZPD_UNICODE_VERSION \"%s\"\n\n" % unicodedata.unidata_version)
    w("/** @brief Inclusive ranges of the code points Python's `re` treats as \\w (str.isalnum() or '_'), sorted. */\n")
    w("static const uint32_t pzpd_unicode_word[%d][2] =\n{\n" % len(words))
    for i in range(0, len(words), 4):
        w("    " + " ".join("{0x%05X,0x%05X}," % (a, b) for a, b in words[i:i + 4]) + "\n")
    w("};\n\n")
    w("/** @brief Code points str.lower() changes: {code point, first, second (0 = none)}, sorted. */\n")
    w("static const uint32_t pzpd_unicode_lower[%d][3] =\n{\n" % len(lower))
    for i in range(0, len(lower), 4):
        w("    " + " ".join("{0x%05X,0x%05X,0x%05X}," % t for t in lower[i:i + 4]) + "\n")
    w("};\n\n#endif // PZPDIR_UNICODE_H_INCLUDED\n")


if __name__ == "__main__":
    main()
